### PR TITLE
Many spelling and code readability improvements.

### PR DESCRIPTION
**Pull request by antaldaniel**
I would like to make some more meaningful commits, but I found the documentation and the code hard to read, so I thought first I would make a pull request with very obvious changes.  None of the changes modify any code.

- Plenty of spelling mistakes are corrected.
- Because the DESCRIPTION sets the spelling to en-US, en-GB spelling was modified to en-US (when multiple uses were present.)
- Some missing Roxygen fields (such as missing @return) values are inserted. In the next CRAN release, this would have triggered a review. 
- When functions were referenced from another package, such as httr::POST, the manual was changed to \code{httr:\link[httr::POST]{POST}} so that manuals are linked per CRAN policy.
- In some cases, I added concise extra URL links or details, particularly with abbreviations that may put off a first-time user; for example, I linked or entirely wrote out QID as Wikidata Q ID (unique ID in Wikidata), linking the official definition.
- Also linked the Wikidata Query Statement Manual with URL.
- When the code or documentation lines exceeded 100 characters, I added extra indentation for code readability.
- When Wikidata was referenced in the text, it followed either the official, capitalized Wikidata spelling or wikidata, I made it Wikidata in the documentation (of course, not in the code and URLs.)

There are a few non-obvious changes that I did not make without asking.
- It would make sense to use usethis::use_spell_check to avoid piling up again hundreds of typos.
- The README is already quite long, but some expressions are not explained to a new user of Wikidata.  I think it would make sense to re-write it with extra detail into 2-3 vignette articles, largely following with a more detailed explanation of the current code divisions, for example, writing a vignette with examples on how to find things on Wikidata programmatically with the Package.
- There are some good coding practices and intentendation rules that would make the code easier to read for a new contributor and improve without changing code functionality. 
- It would be good to add a pkgdown website and install a long-form, standard, HTML manual which is far easier to read than the PDF manual.

### CODE REVIEW

**Comment by hugolpz** [comment]
Hello @TS404 @Ironholds @metacoretechs,

Could you review this PR and, if necessary, grand adminship to @cutterkom . As WikidataR move to open source model and reduced coding intensity, it is important to multiply github administrators so the project stays resilient and reactive to PR.


Also, thank you for this library, I will recommend a group of PhD student its use tomorrow, in a seminar.

**Comment by antaldaniel** [comment]
@hugolpz @Ironholds @metacoretechs  I think that my pull request is absolutely safe, it is not changing functionality. However, I woudl gladly make substantial commits, and even review pull requests. I have about 7 simple and sometimes very complex packages on CRAN and I work together with a postdoc under my supervision.

**Comment by hugolpz** [comment]
I'm not sure this project is open licence and open to PR.
The [licence file](https://github.com/TS404/WikidataR?tab=License-1-ov-file#readme) states :

> YEAR: 2014
> COPYRIGHT HOLDER: Oliver Keyes

@TS404 rightfully follows @Ironholds's [parent project's licence file](https://github.com/Ironholds/WikidataR?tab=License-1-ov-file#readme).

With such licence AND an inactive owner (@TS404) with a single github commit is past 24 months, I'm not sure that current project can move forward.

TS404, if you want to allow others contributors to maintain and push forward WikidataR, please [open this page and invite](https://github.com/TS404/WikidataR/settings/access) @antaldaniel or/and myself as project owner / maintainer. So we can manage forward.

----

[EDIT:] Message [sent](https://www.wikidata.org/wiki/Topic:Yf2whnhg3lp0xf17) to project owner

**Comment by antaldaniel** [comment]
@hugolpz I agree with your concern, and I think that it would be good if @TS404 and @Ironholds would help to resolve this issue. While apparantely it is OK to publish copyright-restricted library extensions on CRAN (though unusual), these two packages in their name refer to three open-source and open knowledge systems, Wikipedia, Wikidata and R.  The MediaWiki/Wikipedia/Wikidata communities would need well-maintained and officially endorsed connectors from R, but these packages are not maintained, not open source, and use the brand names of Wikmedia Foundation.

In my opinion, there would be two ethical ways to resolve this issue:
- [x] @TS404 and @Ironhold make their CRAN packages open source, and allow co-authors, perhaps even a maintainer to keep them working.
- [ ] another possiblity to rename the packages to show their limited usability.

I am planning to develop new packages that seek official endorsement from Wikidata, and I think that this package could be a part of that ecosystem, but it must become open-source and well maintained. The alternative is to build up a new package, but in that case I find it problematic that the name of an officially endorsed package will make a less clear connection than the non-endorsed and not open ones.

I'd gladly paticipate, and also would gladly present a maintainace and development plan that could be vetted by the broader Wikibase developer community (which develops Wikidata.)

**Comment by TS404** [comment]
Hi all - sorry to have missed all this. I've been away from this project for a while and not kept myself up to date. I'd greatly welcome additional admins, so I'll add the following maintainers:
- @cutterkom
- @antaldaniel
- @hugolpz

@Ironhold put the MIT license in the [original readme](https://github.com/Ironholds/WikidataR/blob/master/README.md), so I'm comfortable just updating the license file to reflect that, since I'm pretty sure that was their intention.

**Comment by antaldaniel** [comment]
Thank you very much, excellent news!

**Comment by antaldaniel** [comment]
I wonder if I can get also a write/editor level access to the master repository.  I just made a quick modernisation of the entire documentation to make it more organised and to meet current CRAN standards.  I would also volunteer to go through all remaining issues, and make a new CRAN release just to keep the package up-to-date with new testing, documentation standards as a start.

**Pull request merged**
